export { default as AIInnovation } from './AIInnovation';
export { default as Business } from './Business';
export { default as Directions } from './Directions';
export { default as Hero } from './Hero';
export { default as Partners } from './Partners';
export { default as Philosophy } from './Philosophy';
export { default as Sidebar } from './Sidebar';
export { default as SupplyChain } from './SupplyChain';
export { default as Vision } from './Vision';
